# Generated by Django 4.2 on 2023-10-12 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicleform', '0002_vehicle_distance_travelled_vehicle_fuel_vehicle_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='Something',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Year', models.IntegerField(choices=[(1990, 1990), (1991, 1991), (1992, 1992), (1993, 1993), (1994, 1994), (1995, 1995), (1996, 1996), (1997, 1997), (1998, 1998), (1999, 1999), (2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022), (2023, 2023)], null=True)),
                ('Fuel', models.CharField(choices=[('Petrol', 'Petrol'), ('Diesel', 'Diesel')], max_length=100, null=True)),
                ('Distance_Travelled', models.PositiveIntegerField(null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='Distance_Travelled',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='Fuel',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='Year',
        ),
    ]
