# Generated by Django 4.2 on 2023-10-12 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicleform', '0003_something_remove_vehicle_distance_travelled_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Something',
        ),
    ]
