# Generated by Django 4.2 on 2023-10-12 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Vehicle', '0007_alter_vehicle_vehicle_brand'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Vehicle',
        ),
    ]
